[project]
name = "image-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.poetry.dependencies]
torch = { version = "2.0.1", source = "https://download.pytorch.org/whl/torch_stable.html" }